### ISSUE TITLE
ライセンスが不明瞭

### ISSUE THREAD

**Issue by meso** [SKIPDD/DueDiligence#13]

**Comment by Numero100** [comment]
どこを整理したら分かりやすくなりますか？

**Comment by meso** [comment]
GitHub では、通常リポジトリの直下に LICENSE ファイルを置き、そのファイル内でこのリポジトリのソースコードやドキュメントがどういったライセンスのもとで使用、複製、改変、再頒布が許可されているのかを明記します。
このリポジトリの場合、ソフトウェア（ソースコード）ではなくドキュメントですので、 Gnu Free Document License や Creative Commons などから適切なライセンスを選択するとよいのではないかと思います。

または、使用や複製などを許諾しないという選択肢もありえます。その場合には、その旨を README.md
 内で明記をしてくださった方が勘違いがなくなると思われます。
また、Pull Request などで第三者がコントリビュートした文章について、その部分についての権利がどうなるのかについても明記があると尚よろしいかと思います。

**Comment by Numero100** [comment]
確かにその通りですね！

**Comment by sotayamashita** [comment]
@Numero100 

おそらくこのプロジェクトはオープンソースとは違うと思いますが以下のリンクが参考になると思います。

- https://opensource.guide/starting-a-project/#launching-your-own-open-source-project
- https://opensource.guide/

**Comment by SKIPDD** [comment]
ライセンスに関してCC BY 4.0である旨追記致しました。

**Comment by meso** [comment]
素晴らしいです！
ただ、通常 LICENSE ファイルは .md ではなく、拡張子なしの `LICENSE` というファイル名になるかと思います。
（実際現状の LICENSE.md ファイルも、実際のフォーマットはマークダウンではないですしね）

**Comment by SKIPDD** [comment]
ファイルの拡張子を修正しました。
ご指摘ありがとうございます。
