### ISSUE TITLE
目次にアラビア数字とローマ数字の一貫しない利用について

### ISSUE THREAD

**Issue by EzoeRyou** [SKIPDD/DueDiligence#17]
目次の内、1, 4, 5, 6はアラビア数字、2, 3はローマ数字を使っているがこれは意図的なものか。

    1 対象会社における...
    II．対象技術等毎の...
    Ⅲ．対象会社における...
    4．第三者の権利を...
    5．ガバナンス調査
    6．価値評価

**Comment by SKIPDD** [comment]
ご指摘ありがとうございます。
修正致します。
